name: FootCube
version: ${version}
main: io.github.divinerealms.footcube.FootCube
authors:
  - SmileyCraft
  - neonsh
description: Soccer/Football in MineCraft
depend: [Vault, LuckPerms, ProtocolLib]
softdepend: [PlaceholderAPI]

commands:
  footcube:
    description: Main FootCube command
    usage: /<command> <subcommand>
    aliases: [fc]

  fcadmin:
    description: Admin command
    aliases: [fca]
    permission: footcube.admin

  matches:
    description: Matches command
    aliases: [q]
    default: true
    permission: footcube.matches

  build:
    description: Toggle Build Mode
    permission: footcube.build